targets:
  $default:
    builders:
      dart_mappable_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/gen/{{file}}.mapper.dart'
#      source_gen|combining_builder:
#        generate_for:
#          - lib/**.dart
#        options:
#          build_extensions:
#            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.mapper.dart'